### ISSUE TITLE
ffmpegAPI.playSong throws Uncaught (in promise) Error

### ISSUE THREAD

**Issue by AndrwMan** [cse110-fa22-group4/cse110-fa22-group4#43]
ffmpegAPI.playSong (or its addEventListener() ) throws "Uncaught (in promise) Error:  The argument 'file' cannot be empty. Received ' ' ". Suspected that file path is undefined or empty string but it is set. Set songPath to both relative and absolute paths but still throws error.

**Comment by TheFProjects** [comment]
I found the error. It has nothing to do with the song path. The issue here is that ffplayPath hasn't been initialized yet. This can be solved easily by updating setPath to do so, which I will later today, if not tomorrow.
For now, though, set the ffplayPath to your own ffplayPath if you want to test it. It works

**Comment by liamgolly** [comment]
@TheFProjects is right, and for future clarity error checking and logging has been added to this function to make it clearer what the issue is if something doesn't play.
